### PR TITLE
This 3rd HW

### PR DESCRIPTION
**Pull request by azartnyi**
Okay, now it`s better, sensei?
This is a description for 3rd HW

### CODE REVIEW

**Review by anatoly-karpovich — CHANGES_REQUESTED** [review]
Use const for almost all variables in task 2

**Comment by anatoly-karpovich** [comment]
Still no description in pr)

**Comment by azartnyi** [comment]
> Still no description in pr)

yep, i`m trying, but i forgot to do a PR, and now i`m trying to revert all this s*it

**Comment by anatoly-karpovich** [comment]
> > Still no description in pr)
> 
> yep, i`m trying, but i forgot to do a PR, and now i`m trying to revert all this s*it

It is still an open PR) you can just edit the description) just 2 clicks are here we are)

**Comment by azartnyi** [comment]
> > > Still no description in pr)
> > 
> > 
> > yep, i`m trying, but i forgot to do a PR, and now i`m trying to revert all this s*it
> 
> It is still an open PR) you can just edit the description) just 2 clicks and here we are)

what about now?

**Review by anatoly-karpovich — APPROVED** [review]
Approvto! 🤌🤌

**Pull request merged**
